spring:
  application:
    name: spring-boot-example
  r2dbc:
    username: postgres
    password: postgres
    url: r2dbc:postgresql://localhost:5432/postgres
  liquibase:
    change-log: "classpath:db/changelog/changelog-master.xml"
    user: postgres
    password: postgres
    url: jdbc:postgresql://localhost:5432/postgres


server:
  port: 8080